### ISSUE TITLE
Strange completion candidates

### ISSUE THREAD

**Issue by muffinmad** [proofit404/company-anaconda#28] opened 2018-05-03 09:30 UTC
After https://github.com/proofit404/company-anaconda/commit/f46960ec6aea72496fbb9966a3c126ca989cfd8a company-anaconda gives me strange completions candidates for text followed by colon
<img width="686" alt="screen shot 2018-05-03 at 12 20 19" src="https://user-images.githubusercontent.com/2702727/39569379-bdc75682-4ecd-11e8-8930-36361ec8d743.png">

**Comment by proofit404** [comment] 2018-05-03 10:27
Hi, thanks for the report!

I tried to port `python.el` native prefix function to the `company-anaconda`.

Can you try `company-capf` backend in the same conditions?

It's based on running interactive python process. You can start it with `C-c C-p` key binding.

See https://github.com/proofit404/company-anaconda/issues/15 for original discussion.

Regards, Artem.

**Comment by muffinmad** [comment] 2018-05-03 11:52
```company-capf``` alone in ```company-backends``` don't give such candidates as ```(company-anaconda :with company-capf)``` on first screenshot.

And ```company-anaconda``` alone in ```company-backends``` gives this:
<img width="707" alt="screen shot 2018-05-03 at 14 42 13" src="https://user-images.githubusercontent.com/2702727/39574887-563a33d6-4ee1-11e8-93cd-fdbfd5d4fdbc.png">

Thanks!

**Comment by proofit404** [comment] 2018-05-03 12:42
What candidates `company-capf` give without anaconda-mode?

**Comment by muffinmad** [comment] 2018-05-03 12:45
For text ```zz:``` ```company-capf``` gives no candidates.

**Comment by valignatev** [comment] 2018-06-01 02:57
Just stumbled upon the same issue:
![image](https://user-images.githubusercontent.com/7038954/40818547-ec915678-659a-11e8-8b59-e823275f07b4.png)

Also can reproduce it if putting my cursor after the colon and do `M-x company-begin-backend company-anaconda`
Also confirm, that `company-capf` doesn't provide candidates for this position.

**Comment by proofit404** [comment] 2018-06-04 00:42
Should be fixed now.

**Closed by proofit404** 2018-06-04 00:42 UTC

**Comment by valignatev** [comment] 2018-06-04 02:17
Colons don't trigger completions now, thanks! However, there is one more strange case I stumbled upon:
![image](https://user-images.githubusercontent.com/7038954/40894823-7e192c6e-67ef-11e8-8b72-36c08e0d9c9e.png)

If I hit RET here, 10 will be replaced with `and`. It's much less hurting than completion popup after the colon, but it's still a bit distracting.

Generally, it happens whenever I'm using number constants:
![image](https://user-images.githubusercontent.com/7038954/40895108-d4e8bcfc-67f0-11e8-8863-5a29de2611e1.png).

I don't have any idea when this might be useful (maybe you know), so I think we should detect number boundaries the same way you detect word boundary in the last commit: https://github.com/proofit404/company-anaconda/blob/master/company-anaconda.el#L55-L56

I'll try to do this in a PR

**Comment by valignatev** [comment] 2018-06-04 02:57
It's a little more tricky than just detecting a number, we shouldn't complete when doing
`1|` and `1.|`, where `|` is a cursor. But we should when `1.1|`, because it's ok in case of a floating number:
```python
>>> 11.11.as_integer_ratio()
(781796747813847, 70368744177664)
>>> 11.11.hex()
'0x1.63851eb851eb8p+3'
```
